[package]
name = "remnant"
version = "0.1.0"
authors = ["John VanEnk <sw17ch@gmail.com>"]

[dependencies]
sodiumoxide = "0.2"
clap = "2.33"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bincode = "1.3"
tempdir = "0.3"
